// <auto-generated />
using System;
using IndigoLabs2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndigoLabs2.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230208202026_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndigoLabs2.Models.CSVRegionCases", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Region_ce_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_ce_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ce_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ce_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ce_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ce_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_foreign_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_foreign_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_foreign_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kk_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_kk_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kk_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kk_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kk_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kk_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kp_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_kp_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kp_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kp_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kp_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kp_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kr_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_kr_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kr_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kr_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kr_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_kr_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_lj_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_lj_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_lj_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_lj_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_lj_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_lj_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_mb_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_mb_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_mb_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_mb_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_mb_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_mb_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ms_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_ms_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ms_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ms_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ms_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ms_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ng_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_ng_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ng_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ng_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ng_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_ng_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_nm_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_nm_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_nm_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_nm_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_nm_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_nm_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_po_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_po_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_po_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_po_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_po_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_po_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_sg_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_sg_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_sg_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_sg_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_sg_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_sg_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_unknown_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_unknown_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_unknown_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_za_cases_active")
                        .HasColumnType("int");

                    b.Property<int>("Region_za_cases_confirmed_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_za_deceased_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_za_vaccinated_1st_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_za_vaccinated_2nd_todate")
                        .HasColumnType("int");

                    b.Property<int>("Region_za_vaccinated_3rd_todate")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.ToTable("CSVRegions");
                });

            modelBuilder.Entity("IndigoLabs2.Models.CSVRegionLastWeek", b =>
                {
                    b.Property<double>("AvgDailyCases")
                        .HasColumnType("float");

                    b.Property<int>("NumAllCases")
                        .HasColumnType("int");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CSVRegionLastWeeks");
                });

            modelBuilder.Entity("IndigoLabs2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "000000",
                            Username = "tomas"
                        },
                        new
                        {
                            Id = 3,
                            Password = "000000",
                            Username = "uporabnik01"
                        },
                        new
                        {
                            Id = 4,
                            Password = "000000",
                            Username = "uporabnik02"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
